axon:
  amqp:
    exchange: amq.fanout
  distributed:
    enabled: true
  eventhandling:
    processors:
      createordersaga:
        source: queueMessageSource
      order:
        source: queueMessageSource

eureka:
  client:
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true


spring:
  datasource:
    initial-size: 2
    username: root
    password: root
    sql-script-encoding: UTF-8
    url: jdbc:mysql://127.0.0.1:3306/ordertest?autoReconnect=true&useSSL=false

  #h2
  h2:
    console:
      enabled: false

  #jpa
  jpa:
    database: MYSQL
    database-platform: 'org.hibernate.dialect.MySQL5Dialect  '
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  # rabbitmq
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
